{% set name = "dtool_create" %}
{% set reponame = "dtool-create" %}
{% set author = "jic-dtool" %}
{% set version = "0.23.0" %}
{% set sha256 = "899c3ea30aa582b7b77089cf07516e3635482c06cbf47d3b769db52d31876914" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - dtool_symlink
    - dtool_http
    - ruamel.yaml

test:
  imports:
    - dtool_create
    - dtool_create.dataset
    - dtool_create.publish
    - dtool_create.utils
  commands:
    - dtool create --help
    - dtool name --help
    - dtool readme --help
    - dtool add --help
    - dtool freeze --help
    - dtool copy --help
    - dtool cp --help
    - dtool publish --help

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'dtool CLI commands for creating datasets'

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
