{% set name = "dtool_create" %}
{% set reponame = "dtool-create" %}
{% set author = "jic-dtool" %}
{% set version = "0.23.1" %}
{% set sha256 = "0a16b4651aeff11e054d3deea3d4c61e09cefbdf36714b9fc8e62e3af676a28d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - dtool_symlink
    - dtool_http
    - ruamel.yaml

test:
  imports:
    - dtool_create
    - dtool_create.dataset
    - dtool_create.publish
    - dtool_create.utils
  commands:
    - dtool create --help
    - dtool name --help
    - dtool readme --help
    - dtool add --help
    - dtool freeze --help
    - dtool copy --help
    - dtool cp --help
    - dtool publish --help

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: dtool CLI commands for creating datasets

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
