{% set name = "dtool_create" %}
{% set version = "0.23.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/dtool-create/dtool-create-{{ version }}.tar.gz
  sha256: "9cecb766c3ce3d2a0b10d5317517d3e50df77bf3231fe6c2c0215a9200b8f094"

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - dtool_symlink
    - dtool_http
    - ruamel.yaml

test:
  imports:
    - dtool_create
    - dtool_create.dataset
    - dtool_create.publish
    - dtool_create.utils
  commands:
    - dtool create --help
    - dtool name --help
    - dtool readme --help
    - dtool add --help
    - dtool freeze --help
    - dtool copy --help
    - dtool cp --help
    - dtool publish --help

about:
  home: https://github.com/jic-dtool/dtool-create
  license: MIT
  license_file: LICENSE.rst
  summary: 'dtool CLI commands for creating datasets'
  doc_url: https://github.com/jic-dtool/dtool-create
  dev_url: https://github.com/jic-dtool/dtool-create

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
