{% set name = "dtool_create" %}
{% set version = "0.23.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-create/dtool-create-{{ version }}.tar.gz
  sha256: db03446059fca9c2133adfb017d5d323d02aeec72b63517bc3a66349d7bf3d04

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - dtool_symlink
    - dtool_http
    - ruamel.yaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - dtool_create
    - dtool_create.dataset
    - dtool_create.publish
    - dtool_create.utils
  commands:
    - dtool create --help
    - dtool name --help
    - dtool readme --help
    - dtool add --help
    - dtool freeze --help
    - dtool copy --help
    - dtool cp --help
    - dtool publish --help

about:
  home: https://github.com/jic-dtool/dtool-create
  license: MIT
  license_file: LICENSE.rst
  summary: dtool CLI commands for creating datasets
  doc_url: https://github.com/jic-dtool/dtool-create
  dev_url: https://github.com/jic-dtool/dtool-create

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
