{% set name = "dtool_create" %}
{% set reponame = "dtool-create" %}
{% set author = "jic-dtool" %}
{% set version = "0.23.2" %}
{% set sha256 = "18f5b1c6eb7bd573353d8af09cfd6860474f3d1ae25d42fe07fa83fbc30d2d25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ reponame }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - setuptools
    - dtoolcore
    - dtool_cli
    - dtool_symlink
    - dtool_http
    - ruamel.yaml

test:
  imports:
    - dtool_create
    - dtool_create.dataset
    - dtool_create.publish
    - dtool_create.utils
  commands:
    - dtool create --help
    - dtool name --help
    - dtool readme --help
    - dtool add --help
    - dtool freeze --help
    - dtool copy --help
    - dtool cp --help
    - dtool publish --help

about:
  home: http://github.com/{{ author }}/{{ reponame }}
  license: MIT
  license_file: LICENSE.rst
  summary: dtool CLI commands for creating datasets

  dev_url: https://github.com/{{ author }}/{{ reponame }}

extra:
  recipe-maintainers:
    - pvanheus
