schema_version: 1

context:
  name: dtool_create
  version: "0.23.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/dtool-create/dtool-create-${{ version }}.tar.gz
  sha256: db03446059fca9c2133adfb017d5d323d02aeec72b63517bc3a66349d7bf3d04

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - click
    - setuptools <80
    - dtoolcore
    - dtool_cli
    - dtool_symlink
    - dtool_http
    - ruamel.yaml

tests:
  - python:
      imports:
        - dtool_create
        - dtool_create.dataset
        - dtool_create.publish
        - dtool_create.utils
      pip_check: false
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - dtool create --help
      - dtool name --help
      - dtool readme --help
      - dtool add --help
      - dtool freeze --help
      - dtool copy --help
      - dtool cp --help
      - dtool publish --help

about:
  license: MIT
  license_file: LICENSE.rst
  summary: dtool CLI commands for creating datasets
  homepage: https://github.com/jic-dtool/dtool-create
  repository: https://github.com/jic-dtool/dtool-create
  documentation: https://github.com/jic-dtool/dtool-create

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
