travis:
  secure:
    BINSTAR_TOKEN: mMpJe8OraDbGiNe0naLjnyrLdFnRZsKXva7cGWDLUIu3xPxUdGqhJzJnSlWDwxG0TiDP+EQUg6g1y3R4qebhX2OdX3n3lNs19M3NuoojftfnIvbNJzX1zCQQjwZR6GwxX2p+njbaMe0Dk6A8OF/vFcf0NHgALaD3NkZRcP5D5O3Gca0GlxDBWw9qoupcUEFKSsxSk9Ncnb+Dj/datGondeR1mCm0iNACFPkU+Bgi9AUig86mv3LL+XxewwNO1QCRUgSS1SG3E6FJjdnIQLqCGeaJrEoCvXaheBa69eWwSDxKbHWEDwY8FFvcYV7L2K6+7FUxBZ2w7TnzHU2oV3jN8GApiTv4G4ttsw0jxbzfHWr+LIWC4RxSK7gVry0HGKEJmXju2CeaC9sLtT0ar/Dt81Ar7zuquIMVjFLLGvWMIV5NyV2ebPLU0z58jZfbw7YzgROIpDsTghj+0t4/Em3Gbhk85U+dHvhmhmQfkwiu4sHVnK/YyJ1XTVjFElt97soPghDipGvJ/E9xW5wTJj0fKQqNycyZyCCPXcy/SWA70pMRuHxJfLc9bahN4qM3jriHk5ZymX3uGnk0OofTfbp6iz1MSvJwWQKS+oL2qiXBczgzHhJUx29wRB5T45bqJORX1gltHxsO6myO+iSP3s4hUcEn5oQufkR0wP/XaEgnyTI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
